<?php

use horstoeko\invoicesuite\codelists\InvoiceSuiteCodelistCurrencyCodes;
use horstoeko\invoicesuite\codelists\InvoiceSuiteCodelistDocumentTypes;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteAddressDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteAllowanceChargeDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteContactDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteDocumentHeaderDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteDocumentPositionDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteIdDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteNoteDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitePartyDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitePaymentTermDiscountDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitePaymentTermDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitePeriodDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitePriceGrossDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitePriceNetDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteProductCharacteristicDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteProductDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteQuantityDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteReferenceDocumentDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteReferenceDocumentExtDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteReferenceProductDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteServiceChargeDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteSummationDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuitesummationLineDTO;
use horstoeko\invoicesuite\documents\dto\InvoiceSuiteTaxDTO;
use horstoeko\invoicesuite\InvoiceSuiteDocumentBuilder;
use horstoeko\invoicesuite\validators\InvoiceSuiteXsdDocumentValidator;

require __DIR__ . "/../vendor/autoload.php";


$dtoDocumentHeader = (new InvoiceSuiteDocumentHeaderDTO())
    ->setNumber('R87654321012345')
    ->setDescription('WARENRECHNUNG')
    ->setType(InvoiceSuiteCodelistDocumentTypes::COMMERCIAL_INVOICE->value)
    ->setDate(DateTime::createFromFormat('Ymd', '20241115'))
    ->addNote(new InvoiceSuiteNoteDTO('Es bestehen Rabatt- oder Bonusvereinbarungen.', 'ST3', 'AAK'))
    ->addNote(new InvoiceSuiteNoteDTO('Der Verkäufer bleibt Eigentümer der Waren bis zu vollständigen Erfüllung der Kaufpreisforderung.', 'EEV', 'AAJ'))
    ->addNote(new InvoiceSuiteNoteDTO("MUSTERLIEFERANT GMBH\nBAHNHOFSTRASSE 99\n99199 MUSTERHAUSEN\nGeschäftsführung:\nMax Mustermann\nUSt-IdNr: DE123456789\nTelefon: +49 932 431 0\nwww.musterlieferant.de\nHRB Nr. 372876\nAmtsgericht Musterstadt\nGLN 4304171000002\nWEEE-Reg-Nr.: DE87654321\n", subjectCode: 'REG'))
    ->addNote(new InvoiceSuiteNoteDTO('Leergutwert: 46,50'))
    ->addNote(new InvoiceSuiteNoteDTO('Wichtige Information: Bei Bestellungen bis zum 19.12. ist die Auslieferung bis spätestens 23.12. garantiert.'))
    ->setCurrency(InvoiceSuiteCodelistCurrencyCodes::EURO->value)
    ->addBuyerReference((new InvoiceSuiteIdDTO())
        ->setId('SomeRef'))
    ->addDeliveryTerm((new InvoiceSuiteIdDTO())
        ->setId('1'))
    ->setIsTest(true)
    ->setSellerParty((new InvoiceSuitePartyDTO())
        ->addId((new InvoiceSuiteIdDTO())
            ->setId('549910'))
        ->addGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4333741000005')
            ->setIdType('0088'))
        ->addName('MUSTERLIEFERANT GMBH')
        ->addContact((new InvoiceSuiteContactDTO())
            ->setPhoneNumber('+49 932 431 500')
            ->setEmailAddress('max.mustermann@musterlieferant.de'))
        ->addAddress((new InvoiceSuiteAddressDTO())
            ->setPostcode('99199')
            ->setAddressLine1('BAHNHOFSTRASSE 99')
            ->setCity('MUSTERHAUSEN')
            ->setCountry('DE'))
        ->addTaxRegistration((new InvoiceSuiteIdDTO())
            ->setId('DE123456789')
            ->setIdType('VA')))
    ->setBuyerParty((new InvoiceSuitePartyDTO())
        ->addId((new InvoiceSuiteIdDTO())
            ->setId('009420'))
        ->addGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4304171000002')
            ->setIdType('0088'))
        ->addName('MUSTER-KUNDE GMBH')
        ->addAddress((new InvoiceSuiteAddressDTO())
            ->setPostcode('40235')
            ->setAddressLine1('KUNDENWEG 88')
            ->setCity('DUESSELDORF')
            ->setCountry('DE')))
    ->addBuyerOrderReference((new InvoiceSuiteReferenceDocumentDTO())
        ->setReferenceNumber('B123456789'))
    ->addAdditionalReference((new InvoiceSuiteReferenceDocumentExtDTO())
        ->setReferenceNumber('A456123')
        ->setTypeCode('130'))
    ->setShipToParty((new InvoiceSuitePartyDTO())
        ->addGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4304171088093')
            ->setIdType('0088'))
        ->addName('MUSTER-MARKT')
        ->addContact((new InvoiceSuiteContactDTO())
            ->setDepartmentName('8211'))
        ->addAddress((new InvoiceSuiteAddressDTO())
            ->setPostcode('31157')
            ->setAddressLine1('HAUPTSTRASSE 44')
            ->setCity('SARSTEDT')
            ->setCountry('DE')))
    ->addSupplyChainEvent(DateTime::createFromFormat('Ymd', '20180805'))
    ->addDeliveryNoteReference((new InvoiceSuiteReferenceDocumentDTO())
        ->setReferenceNumber('L87654321012345'))
    ->setInvoiceeParty((new InvoiceSuitePartyDTO())
        ->addId((new InvoiceSuiteIdDTO())
            ->setId('009420'))
        ->addGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4304171000002')
            ->setIdType('0088'))
        ->addName('MUSTER-KUNDE GMBH')
        ->addAddress((new InvoiceSuiteAddressDTO())
            ->setPostcode('40235')
            ->setAddressLine1('KUNDENWEG 88')
            ->setCity('DUESSELDORF')
            ->setCountry('DE')))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setAmount(61.07)
        ->setType('VAT')
        ->setBasisAmount(321.40)
        ->setCategory('S')
        ->setPercent(19.00))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setAmount(8.93)
        ->setType('VAT')
        ->setBasisAmount(127.59)
        ->setCategory('S')
        ->setPercent(7.00))
    ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
        ->setChargeIndicator(false)
        ->setPercent(2.00)
        ->setBaseAmount(280.00)
        ->setAmount(5.60)
        ->setReason('Rechnungsrabatt 1')
        ->setTaxType('VAT')
        ->setTaxCategory('S')
        ->setTaxPercent(19.00))
    ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
        ->setChargeIndicator(false)
        ->setPercent(2.00)
        ->setBaseAmount(130.70)
        ->setAmount(2.61)
        ->setReason('Rechnungsrabatt 1')
        ->setTaxType('VAT')
        ->setTaxCategory('S')
        ->setTaxPercent(7.00))
    ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
        ->setChargeIndicator(false)
        ->setBaseAmount(280.00)
        ->setAmount(2.50)
        ->setReason('Rechnungsrabatt 2')
        ->setTaxType('VAT')
        ->setTaxCategory('S')
        ->setTaxPercent(19.00))
    ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
        ->setChargeIndicator(false)
        ->setBaseAmount(130.70)
        ->setAmount(0.50)
        ->setReason('Rechnungsrabatt 2')
        ->setTaxType('VAT')
        ->setTaxCategory('S')
        ->setTaxPercent(7.00))
    ->addServiceCharge((new InvoiceSuiteServiceChargeDTO())
        ->setDescription('Transportkosten')
        ->setAmount(3.00)
        ->setTaxType('VAT')
        ->setTaxCategory('S')
        ->setTaxPercent(19.00))
    ->addPaymentTerm((new InvoiceSuitePaymentTermDTO())
        ->setDescription('Bei Zahlung innerhalb 14 Tagen gewähren wir 2,0% Skonto.')
        ->addDiscountTerm((new InvoiceSuitePaymentTermDiscountDTO())
            ->setPeriod((new InvoiceSuitePeriodDTO())
                ->setPeriod(14.0)
                ->setPeriodUnit('DAY'))
            ->setDiscountPercent(2.00)))
    ->addSummation((new InvoiceSuiteSummationDTO())
        ->setNetAmount(457.20)
        ->setChargeTotalAmount(3.00)
        ->setDiscountTotalAmount(11.21)
        ->setTaxBasisAmount(448.99)
        ->setTaxTotalAmount(70.00)
        ->setGrossAmount(518.99)
        ->setPrepaidAmount(0.00)
        ->setDueAmount(518.99));

$dtoDocumentPositionOne = (new InvoiceSuiteDocumentPositionDTO())
    ->setLineId('1')
    ->setProduct((new InvoiceSuiteProductDTO())
        ->setGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4123456000014')
            ->setIdType('0160'))
        ->setSellerId('ZS997')
        ->setName('Zitronensäure 100ml')
        ->addCharacteristic((new InvoiceSuiteProductCharacteristicDTO())
            ->setDescription('Verpackungsart')
            ->setValue('BO')))
    ->setGrossPrice((new InvoiceSuitePriceGrossDTO())
        ->setAmount(1.0000))
    ->setNetPrice((new InvoiceSuitePriceNetDTO())
        ->setAmount(1.0000))
    ->setQuantityBilled((new InvoiceSuiteQuantityDTO())
        ->setQuantity(100.0000)
        ->setQuantityUnit('H87'))
    ->setQuantityPackage((new InvoiceSuiteQuantityDTO())
        ->setQuantity(4.0000)
        ->setQuantityUnit('XCT'))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setCategory('S')
        ->setType('VAT')
        ->setPercent(19.0))
    ->setSummation((new InvoiceSuitesummationLineDTO())
        ->setNetAmount(100.00));

$dtoDocumentPositionTwo = (new InvoiceSuiteDocumentPositionDTO())
    ->setLineId('2')
    ->setProduct((new InvoiceSuiteProductDTO())
        ->setGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4123456000021')
            ->setIdType('0160'))
        ->setSellerId('GZ250')
        ->setName('Gelierzucker Extra 250g'))
    ->setGrossPrice((new InvoiceSuitePriceGrossDTO())
        ->setAmount(1.5000)
        ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
            ->setAmount(0.03)
            ->setChargeIndicator(false)
            ->setReason('Artikelrabatt 1'))
        ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
            ->setAmount(0.02)
            ->setChargeIndicator(false)
            ->setReason('Artikelrabatt 2')))
    ->setNetPrice((new InvoiceSuitePriceNetDTO())
        ->setAmount(1.4500))
    ->setQuantityBilled((new InvoiceSuiteQuantityDTO())
        ->setQuantity(50.0000)
        ->setQuantityUnit('H87'))
    ->setQuantityPackage((new InvoiceSuiteQuantityDTO())
        ->setQuantity(1.0000)
        ->setQuantityUnit('XCT'))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setCategory('S')
        ->setType('VAT')
        ->setPercent(7.0))
    ->setSummation((new InvoiceSuitesummationLineDTO())
        ->setNetAmount(72.50));

$dtoDocumentPositionThree = (new InvoiceSuiteDocumentPositionDTO())
    ->setLineId('3')
    ->setProduct((new InvoiceSuiteProductDTO())
        ->setGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4123456000021')
            ->setIdType('0160'))
        ->setSellerId('GZ250')
        ->setName('Gelierzucker Extra 250g')
        ->setDescription('Artikel wie vereinbart ohne Berechnung'))
    ->setGrossPrice((new InvoiceSuitePriceGrossDTO())
        ->setAmount(0.0000))
    ->setNetPrice((new InvoiceSuitePriceNetDTO())
        ->setAmount(0.0000))
    ->setQuantityBilled((new InvoiceSuiteQuantityDTO())
        ->setQuantity(10.0000)
        ->setQuantityUnit('H87'))
    ->setQuantityPackage((new InvoiceSuiteQuantityDTO())
        ->setQuantity(1.0000)
        ->setQuantityUnit('XCT'))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setCategory('S')
        ->setType('VAT')
        ->setPercent(7.0))
    ->setSummation((new InvoiceSuitesummationLineDTO())
        ->setNetAmount(0.00));

$dtoDocumentPositionFour = (new InvoiceSuiteDocumentPositionDTO())
    ->setLineId('4')
    ->setProduct((new InvoiceSuiteProductDTO())
        ->setGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4100130013294')
            ->setIdType('0160'))
        ->setSellerId('2031')
        ->setName('Bierbrau Pils 20/0500')
        ->setDescription('EAN-VKE: 4100130913297')
        ->addCharacteristic((new InvoiceSuiteProductCharacteristicDTO())
            ->setDescription('Verpackung')
            ->setValue('Kiste')))
    ->setGrossPrice((new InvoiceSuitePriceGrossDTO())
        ->setAmount(12.0000))
    ->setNetPrice((new InvoiceSuitePriceNetDTO())
        ->setAmount(12.0000))
    ->setQuantityBilled((new InvoiceSuiteQuantityDTO())
        ->setQuantity(15.0000)
        ->setQuantityUnit('XBC'))
    ->setQuantityPackage((new InvoiceSuiteQuantityDTO())
        ->setQuantity(20.0000)
        ->setQuantityUnit('XBO'))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setCategory('S')
        ->setType('VAT')
        ->setPercent(19.0))
    ->setSummation((new InvoiceSuitesummationLineDTO())
        ->setNetAmount(180.00));

$dtoDocumentPositionFive = (new InvoiceSuiteDocumentPositionDTO())
    ->setLineId('5')
    ->setProduct((new InvoiceSuiteProductDTO())
        ->setGlobalId((new InvoiceSuiteIdDTO())
            ->setId('2001015001325')
            ->setIdType('0160'))
        ->setSellerId('1805')
        ->setName('Leergutpfand 20 x 0,5l')
        ->addCharacteristic((new InvoiceSuiteProductCharacteristicDTO())
            ->setDescription('Verpackung')
            ->setValue('unverpackt')))
    ->setGrossPrice((new InvoiceSuitePriceGrossDTO())
        ->setAmount(3.1000))
    ->setNetPrice((new InvoiceSuitePriceNetDTO())
        ->setAmount(3.1000))
    ->setQuantityBilled((new InvoiceSuiteQuantityDTO())
        ->setQuantity(15.0000)
        ->setQuantityUnit('C62'))
    ->setQuantityPackage((new InvoiceSuiteQuantityDTO())
        ->setQuantity(1.0000)
        ->setQuantityUnit('XBC'))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setCategory('S')
        ->setType('VAT')
        ->setPercent(19.0))
    ->setSummation((new InvoiceSuitesummationLineDTO())
        ->setNetAmount(46.50));

$dtoDocumentPositionSix = (new InvoiceSuiteDocumentPositionDTO())
    ->setLineId('6')
    ->setProduct((new InvoiceSuiteProductDTO())
        ->setGlobalId((new InvoiceSuiteIdDTO())
            ->setId('4123456000038')
            ->setIdType('0160'))
        ->setSellerId('MP107')
        ->setName('Mischpalette Joghurt Karton 3 x 20')
        ->addCharacteristic((new InvoiceSuiteProductCharacteristicDTO())
            ->setDescription('Verpackung')
            ->setValue('Karton'))
        ->addReferenceProduct((new InvoiceSuiteReferenceProductDTO())
            ->setGlobalId((new InvoiceSuiteIdDTO())
                ->setId('4123456001035')
                ->setIdType('0160'))
            ->setSellerId('JOG103')
            ->setName('Erdbeer 20 x 150g Becher')
            ->setUnitQuantity((new InvoiceSuiteQuantityDTO())
                ->setQuantity(20.00000)
                ->setQuantityUnit('C62')))
        ->addReferenceProduct((new InvoiceSuiteReferenceProductDTO())
            ->setGlobalId((new InvoiceSuiteIdDTO())
                ->setId('4123456002032')
                ->setIdType('0160'))
            ->setSellerId('JOG203')
            ->setName('Banane 20 x 150g Becher')
            ->setUnitQuantity((new InvoiceSuiteQuantityDTO())
                ->setQuantity(20.00000)
                ->setQuantityUnit('C62')))
        ->addReferenceProduct((new InvoiceSuiteReferenceProductDTO())
            ->setGlobalId((new InvoiceSuiteIdDTO())
                ->setId('4123456003039')
                ->setIdType('0160'))
            ->setSellerId('JOG303')
            ->setName('Schoko 20 x 150g Becher')
            ->setUnitQuantity((new InvoiceSuiteQuantityDTO())
                ->setQuantity(20.00000)
                ->setQuantityUnit('C62'))))
    ->setGrossPrice((new InvoiceSuitePriceGrossDTO())
        ->setAmount(30.0000)
        ->addAllowanceCharge((new InvoiceSuiteAllowanceChargeDTO())
            ->setAmount(0.90)
            ->setChargeIndicator(false)
            ->setReason('Artikelrabatt 1')))
    ->setNetPrice((new InvoiceSuitePriceNetDTO())
        ->setAmount(29.10000))
    ->setQuantityBilled((new InvoiceSuiteQuantityDTO())
        ->setQuantity(2.0000)
        ->setQuantityUnit('C62'))
    ->setQuantityPackage((new InvoiceSuiteQuantityDTO())
        ->setQuantity(1.0000)
        ->setQuantityUnit('XPX'))
    ->addTax((new InvoiceSuiteTaxDTO())
        ->setCategory('S')
        ->setType('VAT')
        ->setPercent(7.0))
    ->setSummation((new InvoiceSuitesummationLineDTO())
        ->setNetAmount(58.20000));

$dtoDocumentHeader->addPosition($dtoDocumentPositionOne);
$dtoDocumentHeader->addPosition($dtoDocumentPositionTwo);
$dtoDocumentHeader->addPosition($dtoDocumentPositionThree);
$dtoDocumentHeader->addPosition($dtoDocumentPositionFour);
$dtoDocumentHeader->addPosition($dtoDocumentPositionFive);
$dtoDocumentHeader->addPosition($dtoDocumentPositionSix);

$documentBuilder = InvoiceSuiteDocumentBuilder::createByProviderUniqueId('fatturapa');
$documentBuilder->createFromDTO($dtoDocumentHeader);

$validator = InvoiceSuiteXsdDocumentValidator::createFromDocumentBuilder($documentBuilder);
$validator->validate();

echo "\n\n";

foreach ($validator->getErrorMessagesInMessageBag() as $message) {
    echo sprintf("  %s\n", $message->getMessageContent());
}

echo "\n\n";
